CREATE TABLE [dbo].[Modules]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[RefCode] UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT NOT NULL,	
	CONSTRAINT [PK_Modules] PRIMARY KEY CLUSTERED ([Id] ASC)
)
